(function(f,g,p){f.guardFatal(function(){f.when("A","jQuery","a-button").register("fx-atfc-button-utils",function(c,a,b){var d=!1;return{hideButtonAndRenderSpinner:function(b){var c=b.$currentTarget.find(".a-button");c&&c.length&&(d=!0,b="atfc-spinner-"+b.data.asin,c.wrap('<div id="'+b+'" class="atfc-spinner"></div>'),a("#"+b).css({width:c.outerWidth()+"px"}),a("#"+b).css({height:c.outerHeight()+"px"}),c.css("visibility","hidden"))},showButtonAndRemoveSpinner:function(b){var c=b.$currentTarget.find(".a-button");
b=a("#atfc-spinner-"+b.data.asin);c&&c.length&&b&&b.length&&(d=!1,c.css("visibility","visible"),c.unwrap())},shouldDisableButtonClicks:function(){return d}}});f.when("fresh-shared-add-to-cart","ready").register("fresh-add-to-cart",function(c){return{addToFreshCart:function(a){c.addToFreshCart(a,"desktop")}}});f.when("A").register("afx-uatc-proxy",function(c){return function(a){var b="/gp/add-to-cart/json";a.reftag!==p&&(b+="/ref="+a.reftag);c.post(b,{timeout:5E3,params:{"session-id":a.sessionID,
clientName:"SharedFreshHandler",nextPage:"cartitems",ASIN:a.asin,offerListingID:a.offerListingID,useUber:"1",source:"Fresh",ruleSet:"FreshGet"},success:a.success,error:a.error})}});f.when("A").register("afx-get-cart-count",function(c){return function(a){c.post("/gp/api/cart/1.0/get-cart-count.json",{timeout:5E3,params:{sessionID:a.sessionID,clientName:"SharedFreshHandler"},success:a.success,error:a.error})}});f.register("afx-csm-metrics-utils",function(){var c={},a=function(a,
c){g.ue&&g.ue.count&&a&&c&&g.ue.count(a,c)};return{startWidgetTimer:function(a){c[a]=Date.now()},endWidgetTimer:function(b,d){var e=Date.now()-c[b];a(d,e)},setWidgetClickTimestamp:function(a){g.ue&&g.uet&&a&&g.uet("tc",a,{wb:1})},setWidgetTimestamp:function(a,c){g.ue&&g.uet&&a&&c&&g.uet(a,c,{wb:1})},increment:function(a){g.ue&&g.ue.count&&a&&g.ue.count(a,(g.ue.count(a)||0)+1)},setCount:a,sendWidgetMetrics:function(a){g.ue&&g.uex&&a&&g.uex("ld",a,{wb:1})}}});f.register("afx-metrics-helper",
function(){var c={ATFC_COUNT:"afxAddToFreshCartCount",ATFC_SUCCESSFUL_ADD_COUNT:"afxAddToFreshCartSuccessfulAddCount",ATFC_ERROR_MODAL_COUNT:"afxAddToFreshCartErrorModalCount",ATFC_UNEXPECTED_ERROR_COUNT:"afxAddToFreshCartUnexpectedErrorCount",ATFC_LATENCY_SCOPE:"afxAddToFreshCartLatencyScope",ATFC_CTCF:"afxAddToFreshCartCTCF",CLEAR_SLOT_ATFC_CTCF:"afxClearSlotAndAddToFreshCartCTFC",CART_SERVICE_RESPONSE_FALSE:"afxCartServiceResponseIsNotOKErrorCount",ITEM_NOT_AVAILABLE:"afxItemNotAvailableErrorModalCount",
ITEM_PARTIALLY_AVAILABLE:"afxItemPartiallyAvailableErrorModalCount",ITEM_PARTIALLY_AVAILABLE_FOR_RESERVATION:"afxItemPartiallyAvailableErrorModalCount",ADDRESS_NOT_SELECTED:"afxAddressNotSelectedErrorCount",INPUT_INVALID:"afxGeneralErrorModalCount",ITEM_NOT_AVAILABLE_FOR_RESERVATION:"afxItemNotAvailableForReservationErrorModalCount",INTERNAL_SERVER_ERROR:"afxGeneralErrorModalCount",PRICE_UNAVAILABLE:"afxItemNotAvailableErrorModalCount",QUANTITY_OVERFLOW:"afxUniqueItemQuantityOverflowErrorModalCount"};
return{getMetricsForDevice:function(a){var b={};Object.keys(c).forEach(function(d){b[d]=c[d]+":"+a});return b}}});f.when("A","jQuery","a-modal","afx-uatc-proxy","afx-get-cart-count","fx-atfc-button-utils","afx-csm-metrics-utils","afx-metrics-helper","ready").register("fresh-shared-add-to-cart",function(c,a,b,d,e,u,h,m){var l;f.when("EWC").execute("add-to-cart-refresh",function(a){l=a});f.when("nav.getFlyout").execute(function(a){a("ewc")});var q={"itemPrice:priceUnavailable:1":"PRICE_UNAVAILABLE",
"itemDeleted:itemCountOverflow:6":"QUANTITY_OVERFLOW"};return{addToFreshCart:function(n,z){function k(d,e){var h=e||{},u=d.data.sessionID;h.title=d.data.title;h.asin=d.data.asin;h.offerListingID=d.data.offerListingID;h.sessionID=u;var h=a.param(h),f=b.create(d.$currentTarget,{name:"fresh-add-to-cart-modal",url:"/afx/cart/reservation_conflict?"+h});c.on("a:popover:afterUpdatePosition:fresh-add-to-cart-modal",function(a){f.update(c.state("modalAttributes")||{})});f.show();a("#a-popover-lgtbox").css("position",
"fixed");f.$container.css("position","fixed");c.on("a:popover:afterHide:fresh-add-to-cart-modal",function(a){v(u);b.remove(a.popover);c.state.replace("modalAttributes",null)})}function x(a){return a.filter(function(a){return a.statusKey in q})}function y(a,b,c){c+=" returned by UATC is not an array";f.log(c,"Error",b);k(a);n.error(a,"","",c)}function A(b,c){var e=b.data.asin,g=b.data.offerListingID,l=b.data.sessionID,m=b.data.reftag;a.each({title:b.data.title,asin:e,offerListingID:g,sessionID:l},
function(a,c){c===p&&(f.log("fresh-add-to-cart required parameter is missing","Error",a),k(b),n.error(b,void 0,void 0,void 0))});d({asin:e,offerListingID:g,sessionID:l,reftag:m,success:function(d){var e;d&&d.isOK?(e=d.extraErrorInfos)&&e.constructor===Array&&0<e.length?e=!0:(e=d.statusList,e=e&&e.constructor===Array&&0<e.length?(e=x(e))&&0<e.length:!1,e=e?!0:!1):(!d.isOK&&h.increment(r.CART_SERVICE_RESPONSE_FALSE),e=!0);e?(h.increment(r.ATFC_ERROR_MODAL_COUNT),d?d.isOK?(e=d.extraErrorInfos,d=d.statusList,
e&&e.constructor!==Array?y(b,e,"extraErrorInfos"):0<e.length?!e||0>=e.length||(d=e[0],"ADDRESS_NOT_SELECTED"===d.statusCode?(h.increment(r.ADDRESS_NOT_SELECTED),d=a.param({asin:b.data.asin,offerListingID:b.data.offerListingID,quantity:1,redirectURL:document.location.href,ref:"afx_atfc_noaddress"}),document.location.href="/afx/nc/chooseaddress?"+d):(d.itemStatusCode in r&&h.increment(r[d.itemStatusCode]),k(b,{reasonCode:d.itemStatusCode,quantityAdded:d.availableQuantity,quantityRequested:d.requestedQuantity}))):
d&&d.constructor!==Array?y(b,d,"statusList"):0<d.length&&d&&!(0>=d.length)&&(d=x(d))&&0<d.length&&(d=q[d[0].statusKey],k(b,{reasonCode:d}),h.increment(r[d]))):(k(b),n.error(b,"","","isOK returned by UATC is false")):(k(b),n.error(b,"","","No response from UATC"))):(h.increment(r.ATFC_SUCCESSFUL_ADD_COUNT),c(d,l));u.showButtonAndRemoveSpinner(b)},error:function(a,c,d){h.increment(r.ATFC_UNEXPECTED_ERROR_COUNT);k(b);n.error(b,a,c,d);u.showButtonAndRemoveSpinner(b)}})}function B(a){var b=r.ATFC_LATENCY_SCOPE+
Date.now();h.startWidgetTimer(b);var d={token:(c.state("baseWidgetState")||{}).csrfToken};c.post("/afx/slotselection/cancel",{timeout:5E3,params:d,success:function(){A(a,function(a,c){var d=r.CLEAR_SLOT_ATFC_CTCF+":lineItemBucket:"+(a.items&&Math.ceil(a.items.length/5));h.endWidgetTimer(b,d);location.reload()})},error:function(){f.log("Failed to clear reservation")}})}function t(a){e({sessionID:a,success:function(a){a&&a.isOK&&a.total&&w(a.total.numActiveItem)},error:function(){f.log("Failed to get cart count",
"Error",a)}})}function w(a){f.when("nav.setCartCount").execute(function(b){b(a)});f.when("mash").execute(function(b){b.cart&&"function"===typeof b.cart.didUpdate&&b.cart.didUpdate({newCartQuantity:a})})}function v(a){l!==p&&"function"===typeof l.refresh?l.refresh():t(a)}var r=m.getMetricsForDevice(z);c.declarative("fresh-clear-slot","click",function(a){B(a)});c.declarative("fresh-add-to-cart","click",function(a){var b=r.ATFC_LATENCY_SCOPE+Date.now();h.startWidgetTimer(b);u.shouldDisableButtonClicks()||
a.$currentTarget.find("input").is(":disabled")||(u.hideButtonAndRenderSpinner(a),g.amazon&&g.amazon.cordova&&g.amazon.cordova.notification&&g.amazon.cordova.notification.vibrate&&g.amazon.cordova.notification.vibrate(50),h.increment(r.ATFC_COUNT),A(a,function(c,d){var e=r.ATFC_CTCF+":lineItemBucket:"+(c.items&&Math.ceil(c.items.length/5));h.endWidgetTimer(b,e);v(d);n.success(a,c)}))})}}})})()})(function(){var f=window.AmazonUIPageJS||window.P,g=f._namespace||f.attributeErrors;return g?g("FreshExperienceAddToCartAssets"):
f}(),window);